services:
  postgres:
    image: postgres
    container_name: db
    restart: always
    user: postgres
    volumes:
      - ./db-data:/var/lib/postgresql
    env_file:
      - .env.development
    environment:
      - POSTGRES_DB=hono
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env.development
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: db@mail.db
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./pgadmin:/var/lib/pgadmin

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/bitnami/minio/data"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=mysecretpassword
      - MINIO_DEFAULT_BUCKETS=mybucket
    command: server --address ":9001" --console-address ":9000" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  minio_data:
